# OneTools Python 配置文件

# 应用设置
app_name: "OneTools"
app_version: "2.0.0"
debug: true
environment: "development"

# 数据库配置
database:
  # SQL Server (主数据库)
  sqlserver_host: "localhost\\SQLEXPRESS"
  sqlserver_port: 1433
  sqlserver_database: "OneToolsDb"
  sqlserver_trusted_connection: true
  sqlserver_username: null
  sqlserver_password: null
  
  # SQLite (配置数据库)
  sqlite_path: "data/onetools.db"
  
  # 连接池设置
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# 服务器配置
server:
  host: "0.0.0.0"
  port: 15008
  reload: true
  workers: 1
  
  # CORS设置
  cors_origins: ["*"]
  cors_methods: ["*"]
  cors_headers: ["*"]

# 日志配置
logging:
  level: "INFO"
  format: "console"  # console 或 json
  file_path: "logs/onetools.log"
  max_file_size: "10MB"
  backup_count: 5

# 模块配置
modules:
  enabled_modules:
    - "transaction_query"
    - "custom_query"
    - "dynamic_query"
  auto_discovery: true
  cache_enabled: true
  cache_ttl: 300


# 其他设置
hot_reload_enabled: true

# MCP (Multi-turn Conversation Protocol) for Playwright configuration
mcp:
  host: "127.0.0.1"
  port: 15009 # Different from the main server port
  enabled: true
  browser: "chromium" # or "firefox", "webkit"
  headless: true